# Generated by Django 5.0.1 on 2024-11-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunnels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltunnelrequest',
            name='ike_version',
            field=models.CharField(choices=[('1', 'IKEv1'), ('2', 'IKEv2')], default='2', max_length=1),
        ),
        migrations.AddField(
            model_name='historicaltunnelrequest',
            name='pre_shared_key',
            field=models.CharField(default='dadadadadads', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tunnelrequest',
            name='ike_version',
            field=models.CharField(choices=[('1', 'IKEv1'), ('2', 'IKEv2')], default='2', max_length=1),
        ),
        migrations.AddField(
            model_name='tunnelrequest',
            name='pre_shared_key',
            field=models.CharField(default='dsadadadada', max_length=255),
            preserve_default=False,
        ),
    ]
