# Generated by Django 5.0.1 on 2024-11-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunnels', '0002_historicaltunnelrequest_ike_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltunnelrequest',
            name='partner_name',
            field=models.CharField(default='adadad', help_text='Name of the partner organization', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaltunnelrequest',
            name='support_desk_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Support/Helpdesk Email'),
        ),
        migrations.AddField(
            model_name='historicaltunnelrequest',
            name='support_desk_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Support/Helpdesk Phone'),
        ),
        migrations.AddField(
            model_name='historicaltunnelrequest',
            name='technical_poc_email',
            field=models.EmailField(default='dasdad', max_length=254, verbose_name='Technical Point of Contact Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaltunnelrequest',
            name='technical_poc_name',
            field=models.CharField(default='dasdadad', max_length=100, verbose_name='Technical Point of Contact Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaltunnelrequest',
            name='technical_poc_phone',
            field=models.CharField(default='dasdasdsda', max_length=20, verbose_name='Technical Point of Contact Phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tunnelrequest',
            name='partner_name',
            field=models.CharField(default='adadada', help_text='Name of the partner organization', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tunnelrequest',
            name='support_desk_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Support/Helpdesk Email'),
        ),
        migrations.AddField(
            model_name='tunnelrequest',
            name='support_desk_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Support/Helpdesk Phone'),
        ),
        migrations.AddField(
            model_name='tunnelrequest',
            name='technical_poc_email',
            field=models.EmailField(default='dadasdad', max_length=254, verbose_name='Technical Point of Contact Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tunnelrequest',
            name='technical_poc_name',
            field=models.CharField(default='dasdasda', max_length=100, verbose_name='Technical Point of Contact Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tunnelrequest',
            name='technical_poc_phone',
            field=models.CharField(default='dadadad', max_length=20, verbose_name='Technical Point of Contact Phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaltunnelrequest',
            name='notification_dl',
            field=models.EmailField(help_text='Internal distribution list for notifications', max_length=254, verbose_name='Notification Distribution List'),
        ),
        migrations.AlterField(
            model_name='historicaltunnelrequest',
            name='service_owner',
            field=models.EmailField(help_text='Internal user email of the service owner', max_length=254),
        ),
        migrations.AlterField(
            model_name='tunnelrequest',
            name='notification_dl',
            field=models.EmailField(help_text='Internal distribution list for notifications', max_length=254, verbose_name='Notification Distribution List'),
        ),
        migrations.AlterField(
            model_name='tunnelrequest',
            name='service_owner',
            field=models.EmailField(help_text='Internal user email of the service owner', max_length=254),
        ),
    ]
