# Generated by Django 5.0.1 on 2024-11-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunnels', '0003_historicaltunnelrequest_partner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltunnelrequest',
            name='approval_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tunnelrequest',
            name='approval_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicaltunnelrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SECURITY_REVIEW', 'Security Review'), ('NETWORK_REVIEW', 'Network Review'), ('APPROVED', 'Approved'), ('PROVISIONED', 'Provisioned'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('DECOMMISSIONED', 'Decommissioned')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='tunnelrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SECURITY_REVIEW', 'Security Review'), ('NETWORK_REVIEW', 'Network Review'), ('APPROVED', 'Approved'), ('PROVISIONED', 'Provisioned'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('DECOMMISSIONED', 'Decommissioned')], default='PENDING', max_length=20),
        ),
    ]
